apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-produto
spec:
  replicas: 10
  selector:
    matchLabels:
      app: api-produto
  template:
    metadata:
      labels:
        app: api-produto
    spec:
      containers:
      - name: api-produto
        image: prissie/api-bootcamp-produto:v2
        resources:
          limits:
            memory: "256Mi"
            cpu: "512m"
        ports:
        - containerPort: 8080
        env:
        - name: MONGODB_URI
          value: mongodb://mongouser:mongopwd@mongodb-service:27017/admin